// configure BadgerFit website
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');

const app = express();

app.use(cors());
app.use(express.json());

// Serve all HTML/CSS/JS files statically from the project root
app.use(express.static(path.join(__dirname)));

// Routes
app.use('/api/match', require('./routes/match'));
app.use('/api/gyms',  require('./routes/gyms'));

// Expose the browser Maps key to the frontend.
// This key ends up in page source, so it must be a *separate*, HTTP-referrer-restricted
// key — never the server-side Places/Geocoding key that bills against this project.
app.get('/api/maps-key', (req, res) => {
  const key = process.env.GOOGLE_MAPS_BROWSER_KEY;
  if (!key) {
    return res.status(500).json({
      error: 'GOOGLE_MAPS_BROWSER_KEY is not set. Add a referrer-restricted browser key to .env.'
    });
  }
  res.json({ key });
});

const IMAGES_DIR = path.join(__dirname, 'images');

// Google place IDs are URL-safe base64-ish; anything else is not ours to look up.
const PLACE_ID_PATTERN = /^[A-Za-z0-9_-]{1,255}$/;

// Image not found — send a generic gym fallback
const FALLBACKS = [
  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=700&h=400&fit=crop',
  'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=700&h=400&fit=crop',
  'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=700&h=400&fit=crop',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&h=400&fit=crop',
  'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=700&h=400&fit=crop',
];

function pickFallback(seed) {
  const hash = Math.abs([...seed].reduce((a, c) => a + c.charCodeAt(0), 0));
  return FALLBACKS[hash % FALLBACKS.length];
}

// Serve locally stored gym images (generated by Fetchimages.js)
// Usage: GET /api/gym-photo?placeId=ChIJ...
app.get('/api/gym-photo', (req, res) => {
  // A repeated ?placeId= gives an array, not a string — take the first value.
  const raw = req.query.placeId;
  const placeId = Array.isArray(raw) ? raw[0] : raw;

  if (typeof placeId !== 'string' || placeId === '') {
    return res.status(400).json({ error: 'Missing placeId' });
  }

  // Reject anything that could walk out of images/ before touching the filesystem.
  if (!PLACE_ID_PATTERN.test(placeId)) {
    return res.status(400).json({ error: 'Invalid placeId' });
  }

  const imgPath = path.join(IMAGES_DIR, `${placeId}.jpg`);

  if (fs.existsSync(imgPath)) {
    res.setHeader('Cache-Control', 'public, max-age=604800'); // 1 week
    return res.sendFile(imgPath);
  }

  res.redirect(pickFallback(placeId));
});
// start BadgerFit and send message to terminal
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`✅ BadgerFit server running at http://localhost:${PORT}`);
});